CREATE DATABASE dbElectrodomesticos;
USE dbElectrodomesticos;

CREATE TABLE  CLIENTE
(
    CODCLI char(4),
    NOMCLI varchar(60),
    APECLI varchar(80),
    EMACLI varchar(80),
    CELCLI char(9),
    DIRCLI varchar(70),
    ESTCLI char(1),

);

CREATE TABLE VENDEDOR
(
    CODVEND char(4),
    NOMVEND varchar(60),
    APEVEND varchar(80),
    EMAVEND varchar(80),
    CELVEND char(9),
    DIRVEND varchar(70),
    ESTVEND char(1),
);

CREATE TABLE PRODUCTO 
(
    CODPRO CHAR(5),
    DESCPRO VARCHAR(80),
    CATPRO CHAR(1),
    PREPRO DECIMAL(8,2),
    STOCKPRO INT,
    ESTPTRO CHAR(1),
	CONSTRAINT CODPRO_PK PRIMARY KEY (CODPRO)

);
CREATE TABLE PROVEEDOR
(
    CODPROV CHAR(5),
    RAZSOCPROV VARCHAR(90),
    RUCPROV VARCHAR(11),
    EMAPROV VARCHAR(70),
    ESTPROV CHAR(1),
	CONSTRAINT CODPROV_PK PRIMARY KEY (CODPROV)

);
CREATE TABLE VENTA
(
    CODVEN CHAR(5),
    FECVEN DATETIME,
    CODCLI CHAR(4),
    CODVEND CHAR(4),
    ESTVEN CHAR(1),
    CONSTRAINT CODVEN_PK PRIMARY KEY (CODVEN)


);
CREATE TABLE VENTADETALLE
(
    IDVENDET INT,
    CODVEN CHAR(5),
    CODPRO CHAR(5),
    CANTPRO INT,
    CONSTRAINT IDVENDET_PK PRIMARY KEY(IDVENDET)

);
 CREATE TABLE COMPRA
 (
    CODCOM CHAR(5),
    FECCOM DATETIME,
    CODVEND CHAR(4),
    CODPROV CHAR(5),
    ESTCOM CHAR(1),
    CONSTRAINT CODCOM_PK PRIMARY KEY (CODCOM)

 );
 CREATE TABLE COMPRADETALLE
 (
    IDCOMDET INT,
    CODCOM CHAR(5),
    CODPRO CHAR(5),
    CANTPRO INT,
    CONSTRAINT IDCOMDET_PK PRIMARY KEY (IDCOMDET)
 );

 -- Relaciones
ALTER TABLE VENTA
ADD CONSTRAINT CODCLI_FK
FOREIGN KEY (CODCLI) REFERENCES CLIENTE (CODCLI);

ALTER TABLE VENTA
ADD CONSTRAINT CODVEND_FK
FOREIGN KEY (CODVEND) REFERENCES VENDEDOR (CODVEND);

ALTER TABLE VENTADETALLE
ADD CONSTRAINT CODVEN_FK
FOREIGN KEY (CODVEN) REFERENCES VENTA (CODVEN);

ALTER TABLE VENTADETALLE
ADD CONSTRAINT CODPRO_FK
FOREIGN KEY (CODPRO) REFERENCES PRODUCTO (CODPRO);

ALTER TABLE COMPRADETALLE
ADD CONSTRAINT CODPROD_FK
FOREIGN KEY (CODPRO) REFERENCES PRODUCTO (CODPRO);

ALTER TABLE COMPRADETALLE
ADD CONSTRAINT CODCOM_FK
FOREIGN KEY (CODCOM) REFERENCES COMPRA (CODCOM);

ALTER TABLE COMPRA
ADD CONSTRAINT CODPROV_FK
FOREIGN KEY (CODPROV) REFERENCES PROVEEDOR (CODPROV);

ALTER TABLE COMPRA
ADD CONSTRAINT CODVENDE_FK
FOREIGN KEY (CODVEND) REFERENCES VENDEDOR (CODVEND);